spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
    username: innowise-user
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    liquibase: DEBUG